### ISSUE TITLE
TwitchAPI not settable?

### ISSUE THREAD

**Issue by WoweePaw** [TwitchLib/TwitchLib#398] opened 2018-05-15 02:43 UTC
Using v2.1.2

Title say's it all ... I just seem to not being able to set my ClientID etc. and application hangs on TwitchAPI api = new TwitchAPI(); (nothing happens anymore)

Code:
```c
        private async void GetChannelId()
        {
            TwitchAPI api = new TwitchAPI();
            api.Settings.ClientId = "myClientId";
            api.Settings.AccessToken = AppSettings.OAuthToken;

            var channel = await api.Channels.v5.GetChannelAsync();
            Console.WriteLine(channel.Id);
        }
```

Would love to hear from you soon since this annoys me a lot ... can't see why this is not working >_> (worked well in 1.6.1)

**Comment by Mahsaap** [comment] 2018-05-15 02:58
That should work, looks like mine. If its hanging on the new call. Maybe uninstall all the variants of twitchlib you have and reinstall the new one. There has been some issues with updating from V1 to V2 in that way.

**Comment by Mahsaap** [comment] 2018-05-15 03:03
i will note the async call in the void method

**Comment by D3thw0lf** [comment] 2018-05-15 03:09
yeah sorry missed that one but this hasn't fixed it. :(

(reinstalled, too)

Application still won't cast the console output. :/

**Comment by swiftyspiffy** [comment] 2018-05-15 03:44
So I wrote up a quick console app to test this endpoint. Excuse the .Result usage (usage in Main)
![4528ky758](https://user-images.githubusercontent.com/9569194/40035624-cf5ba20e-57bf-11e8-8160-b143360e83e0.png)

**Comment by D3thw0lf** [comment] 2018-05-15 03:54
I'm trying a console app now ... WPF not working for whatever reason code is exactly the same what you guys written. :/

**Comment by Mahsaap** [comment] 2018-05-15 04:33
it's fine I just don't know why.

**Comment by swiftyspiffy** [comment] 2018-05-15 04:38
No problem :) and I honestly have no clue. I’ve done very little work with regards to WPF.

**Comment by D3thw0lf** [comment] 2018-05-15 04:52
Ok seems to work in TwitchLib.Api v 2.1.0

Code:
```c
using System;
using System.Windows;
using TwitchLib.Api;

namespace TestApp
{
    /// <summary>
    /// Interaktionslogik für MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Test();
        }

        private async void Test()
        {
            TwitchAPI api = new TwitchAPI();
            await api.Settings.SetClientIdAsync("ClientID");
            await api.Settings.SetAccessTokenAsync("OAuthToken");

            var channel = await api.Channels.v5.GetChannelAsync();
            Console.WriteLine(channel.Id);
            Console.WriteLine(channel.DisplayName);
            Console.WriteLine(channel.Status);
        }
    }
}
```

**Comment by Mahsaap** [comment] 2018-05-15 14:35
What exactly is failing? I can make an instance of TwitchAPI no problem with WPF?
What framework are you using? Have you tried another API call just in case its that one?

**Comment by D3thw0lf** [comment] 2018-05-15 14:47
Yip tried other endpoints etc. ChatClient is working fine btw. just the TwitchAPI Stuff is not working (for me). It seems like it's not using the ClientID and Access Token set on v2.1.2 with the exact same code working on a Console App (Screenshot).

I'm on NET Framework 4.6.2 with WPF 4.7 
I also updated my Visual Studio today to make sure it's not a Problem on this end but as I mentioned just two versions below (v.2.1.0) API is working fine and as intended again (for me).

**Comment by Mahsaap** [comment] 2018-05-15 15:15
Where are you getting SetClientIdAsync? thats not even found in the API github

**Comment by Mahsaap** [comment] 2018-05-15 15:28
Well at least you have a version that works. I'm pretty much lost on ideas now. One more question did you try 2.1.1 also? just to try and pin point more where the change may have happened.

**Comment by swiftyspiffy** [comment] 2018-05-17 23:46
Going to go ahead and close this. Feel free to reopen as needed.

**Closed as completed** 2018-05-17 23:47 UTC
