### ISSUE TITLE
TwitchLib.Client.Exceptions.BadStateException: Must be connected to at least one channel.

### ISSUE THREAD

**Issue by mgould1799** [TwitchLib/TwitchLib#445] opened 2019-03-27 23:54 UTC
I am trying to write a function like 

`void SayMessage(String channel, String message)
        {
            client.SendMessage(channel, message);
        }`

I connect the bot first with the self written connect method. Right after I call the SayMessage method and can't the error  TwitchLib.Client.Exceptions.BadStateException: Must be connected to at least one channel.

I have tried adding the client.JoinChannel(channel_name) within the Connect method. It worked at one point. However, it just now does not connect at all.

**Comment by DarkoreXOR** [comment] 2019-11-21 17:51
I have the same exception when I try send something via `SendMessage()` method.

When I use the `client.Initialize()` method with the channel parameter for auto-joining, it works fine, but when I handle the `OnConnected` event and then I call the `JoinChannel()` method in the event, it raises the `OnJoinedChannel` event first and also it raises the `OnFailureToReceiveJoinConfirmation` event second, and after that I have an empty `client.JoinedChannels` collection. 

P.S. The client works even with the empty `client.JoinedChannels` collection. The `OnMessageReceived` event raises when I write something in the chat. But I can't send a response back.

I'm using TwitchLib.Client from nuget, version 3.1.4

**Comment by swiftyspiffy** [comment] 2019-11-21 18:02
Will look into this tonight. Can you post snippets from your code relevant to this?

**Comment by DarkoreXOR** [comment] 2019-11-21 18:31
[screenshot with demonstration](http://prntscr.com/q08ceu)

```CSharp
using System;
using System.Collections.Generic;
using TwitchLib.Client;
using TwitchLib.Client.Models;

namespace TestApp
{
    class Program
    {
        private static readonly List<string> Channels = new List<string>()
        {
            "DarkoreXOR"
        };

        static void Main(string[] args)
        {
            var client = new TwitchClient();
            var credentials = new ConnectionCredentials("darkorebot", "<my oauth key>");

            client.Initialize(credentials);

            client.OnJoinedChannel += OnJoinedChannel;
            client.OnFailureToReceiveJoinConfirmation += OnFailureToReceiveJoinConfirmation;
            client.OnConnected += OnConnected;
            client.OnMessageReceived += OnMessageReceived;

            client.Connect();

            Console.ReadLine();
        }

        private static void OnJoinedChannel(object sender, TwitchLib.Client.Events.OnJoinedChannelArgs e)
        {
            Console.WriteLine("[OnJoined]");
            Console.WriteLine($"  >> channel: {e.Channel}");
            Console.WriteLine();
        }

        private static void OnFailureToReceiveJoinConfirmation(object sender, TwitchLib.Client.Events.OnFailureToReceiveJoinConfirmationArgs e)
        {
            Console.WriteLine("[OnFailureToReceiveJoinConfirmation]");
            Console.WriteLine($"  >> channel: {e.Exception.Channel}");
            Console.WriteLine($"  >> details: {e.Exception.Details}");
            Console.WriteLine();
        }

        private static void OnConnected(object sender, TwitchLib.Client.Events.OnConnectedArgs e)
        {
            Console.WriteLine("[OnConnected]");
            Console.WriteLine($"  >> bot: {e.BotUsername}");
            Console.WriteLine();

            var client = (TwitchClient) sender;

            Channels.ForEach(channel => client.JoinChannel(channel));
        }

        private static void OnMessageReceived(object sender, TwitchLib.Client.Events.OnMessageReceivedArgs e)
        {
            Console.WriteLine("[OnMessageReceived]");
            Console.WriteLine($">> channel: {e.ChatMessage.Channel}");
            Console.WriteLine($">> message: {e.ChatMessage.Message}");
            Console.WriteLine();

            var client = (TwitchClient) sender;

            client.SendMessage(e.ChatMessage.Channel, "hello, world");
        }
    }
}
```

**Comment by swiftyspiffy** [comment] 2019-11-22 03:52
Following up on this, I am getting that event (`OnFailureToReceiveJoinConfirmation`), but am still joining the channel as expected. Going to see why the event is firing now.

**Comment by swiftyspiffy** [comment] 2019-11-22 04:07
Issue is here:
https://github.com/TwitchLib/TwitchLib.Client/blob/4c3208e864758e34052de3ee8a827f19959e18ad/TwitchLib.Client/TwitchClient.cs#L1300-L1301

The root cause is that this is case sensitive, and whenever the join channel is not lowercase, it'll fail to remove the channel from the `_awaitingJoins` list. The fix right now is to lowercase the channel in your `Channels` list. I'm getting a fix to dev branch now for it.

**Comment by swiftyspiffy** [comment] 2019-11-22 04:15
Fixed here: https://github.com/TwitchLib/TwitchLib.Client/commit/cf70fd891fea8a8a19e9f06754e0f0b2c5496d34

**Comment by swiftyspiffy** [comment] 2019-11-22 04:16
Will close this. Feel free to reopen if needed.

**Closed as completed by swiftyspiffy** 2019-11-22 04:16 UTC
