### ISSUE TITLE
Missing command

### ISSUE THREAD

**Issue by ghost** [TwitchLib/TwitchLib#1114] opened 2023-02-25 10:25 UTC
[25.02.2023 17:23:33] Unaccounted for: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #general_hs_ :Unrecognized command: /vips (please create a TwitchLib GitHub issue :P)
[25.02.2023 17:23:33] Received: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #general_hs_ :Unrecognized command: /mods
[25.02.2023 17:23:33] Unaccounted for: @msg-id=unrecognized_cmd :tmi.twitch.tv NOTICE #general_hs_ :Unrecognized command: /mods (please create a TwitchLib GitHub issue :P)

**Comment by Hampo** [comment] 2023-02-25 10:26
Duplicate of #1113

**Comment by swiftyspiffy** [comment] 2023-04-07 14:38
The other issue is closed, so I'll go ahead and close this one. Thank you @Hampo for the deprecation change https://github.com/TwitchLib/TwitchLib.Client/commit/01edbf25dc9a228a3022fe6fefc018841df8368b

**Closed as completed by swiftyspiffy** 2023-04-07 14:38 UTC
Labels: Client

**Comment by Hampo** [comment] 2023-04-07 14:40
> The other issue is closed, so I'll go ahead and close this one. Thank you @Hampo for the deprecation change https://github.com/TwitchLib/TwitchLib.Client/commit/01edbf25dc9a228a3022fe6fefc018841df8368b 

That one wasn't me, that was @Foretack

**Comment by swiftyspiffy** [comment] 2023-04-07 16:00
Oops, my bad!
