### ISSUE TITLE
Stuck if WPF

### ISSUE THREAD

**Issue by ianw12345** [TwitchLib/TwitchLib#1062] opened 2021-11-04 17:06 UTC
I develop a WPF .Net 6.0 Application, but it seems, that twitchlib doesn't work within WPF. If I use the same code in a console-application, everything works like a charm. 

`using System.Windows;
using TwitchLib.Api;

namespace WpfApp3
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private static TwitchAPI twitchAPI;

        public MainWindow()
        {
            InitializeComponent();

            twitchAPI = new TwitchAPI();
            twitchAPI.Settings.ClientId = "111";
            twitchAPI.Settings.Secret = "11111";
            var x = twitchAPI.Auth.GetAccessToken();//<= This code takes forever

            //Checks subscription for a specific user and the channel specified.

           
        }
    }
}
`

Here the same working code another app:
`
using TwitchLib.Api;

namespace Example
{
    class Program
    {
        private static TwitchAPI api;

        public static void Main()
        {
            api = new TwitchAPI();
            api.Settings.ClientId = "111";
            api.Settings.Secret = "1111";
            var x = api.Auth.GetAccessToken();

            Console.ReadKey();
        }

    }
}`

Does have anyone any idea or help?

Thx
Ian

**Comment by Mahsaap** [comment] 2021-11-04 18:11
I think your not on the latest, because that call is not in that namespace. But also the one in that name space is async and should not be called in a UI class.

**Comment by Mahsaap** [comment] 2021-11-04 18:13
The library is also .netstandard 2

**Comment by ianw12345** [comment] 2021-11-04 23:02
This is just an example and not the real "not" working code. It also doesn't matter if it is in the UI or outside. I have a class, which should handle all the Twitch calls, but it also stuck. I have the same problems as described in Ticket #399

**Comment by Syzuna** [comment] 2021-11-04 23:05
Interesting as it was reported as fixed by the issue creator back then. will take another look

**Comment by Syzuna** [comment] 2021-11-04 23:15
might have found the cause for this already. will try to fix it and would be nice if you could then try the prerelease version after I pushed the fix for me

**Comment by ianw12345** [comment] 2021-11-04 23:16
After hitting the breakpoint and press F10 it will be in this situation. Profiler is running and no exception is thrown.

![image](https://user-images.githubusercontent.com/42937336/140433088-18b917d9-6e9a-4ee4-b1ed-d8b67e3ed641.png)

**Comment by prom3theu5** [comment] 2021-11-04 23:49
While Syzuna is looking into a fix, I'll tell you why it occurs in the current nuget release / preview :)

The problem here is you are calling the initialisation in the constructor of a UI thread, which is largely a one-thread-at-a-time context.
Far down the call stack, GetAccessToken calls Getawaiter().GetResult(), without ConfigureAwait(false).

Because of this, you are going to have to get a little messy if calling this inside a UI class like the class backing of a window.
The following should work (Untested).

```
public partial class MainWindow
{
  private readonly TwitchAPI _twitchApi;

  public MainWindow()
  {
    InitializeComponent();
    _twitchApi = new TwitchAPI();
    Initialize();
  }

  private void Initialize()
  {
     Task.Run(() =>
       {
         _twitchApi.Settings.ClientId = "111";
         _twitchApi.Settings.Secret = "11111";
         var x = _twitchApi.Auth.GetAccessToken();
         // do something with X
         Debug.WriteLine("finished.");
       }).ConfigureAwait(false);
  }
```

You could however call things normally from a none UI ViewModel class fine if you utilise an MVVM approach to your app design.

**Comment by ianw12345** [comment] 2021-11-04 23:56
Thanks @prom3theu5 works great!

**Comment by Syzuna** [comment] 2021-11-05 00:05
hmm yeah the changes I made in a local copy wont work in a constructor as well as all I did was make them async across the board and dont force any synchronous runs of async methods deep down in the code. 

but code like that shouldnt go in an UI Element constructor anyway but in the backing ViewModel of that element as Prometheus recommended

**Closed as completed** 2021-11-05 22:01 UTC
