### ISSUE TITLE
TwitchAPI (helix) async methods not returning into context

### ISSUE THREAD

**Issue by Iturio** [TwitchLib/TwitchLib#399] opened 2018-05-17 08:50 UTC
Hi folks,

today I upgraded the TwitchAPI from "v2.1.0" to "v2.1.2". After that I realized, that none of the async methods (I tried and tested the helix API with: "GetUsersAsync", "GetStreamsAsync") are able to return into the issuing main context (which was no problem with "v2.1.0"). As soon as the method gets called (and awaited) the whole application just seems to deadlock itself (it just loads forever and doesn't return into the main context). This behaviour only occurs while the API is used in an **ASP.NET Web Application (MVC 5 with .NET 4.6.2)**.

**I already tried the following**:
- Build a test console Application and called the same methods here (**here it's working without any problems**)

```
static ITwitchAPI TwitchApi = new TwitchAPI();
private static GetUsersResponse _result;

static void Main(string[] args)
{
    TwitchApi.Settings.ClientId = "...";
    Task t = MainAsync();
    t.Wait();

    Console.WriteLine(_result?.Users?.SingleOrDefault()?.DisplayName);
}

static async Task MainAsync()
{
    _result = await TwitchApi.Users.helix.GetUsersAsync(accessToken: "...");
}
```
- Build a small MVC test application without DI or any other stuff (**here it's not working**)
```
public class DefaultController : Controller
{
    protected readonly ITwitchAPI TwitchApi;

    public DefaultController()
    {
        TwitchApi = new TwitchAPI();
        TwitchApi.Settings.ClientId = "...";
    }

    // GET: Default
    public async Task<ActionResult> Index()
    {
        var result = await this.TwitchApi.Users.helix.GetUsersAsync(accessToken: "...");
        string userName = result?.Users?.SingleOrDefault()?.DisplayName;
        return View(model: userName);
    }
}
```
As soon as "GetUsersAsync" is hit, the app deadlocks itself and loads forever. I've also verified the same behaviour with TwitchAPI "v2.1.1" and found this issue about a **similar problem with WPF applications** (it seems as if the problem only occurs in real async contexts, so console apps are not affected): https://github.com/TwitchLib/TwitchLib/issues/398

I didn't manage to analyse your source code and track down the root of that problem yet. Do you have any ideas or hints in the meanwhile?

*Edit*: By monitoring the network traffic with Fiddler I can see that the API successfuly reaches the Twitch Endpoint and Twitch answers with a correct result.

**Comment by LuckyNoS7evin** [comment] 2018-05-17 09:28
The following code, returned the result I expected in "very little" time, no locking, however this is dotnet core. I have tried the same in Full Framework and came across the same issue as you. It looks to be an issue with Full Framework only. If none of the others get to this before I do tonight, I'll have a look at this one on stream

```  [Route("api/[controller]")]
    public class ValuesController : Controller
    {
        protected readonly ITwitchAPI _twitchApi;

        public ValuesController(ITwitchAPI twitchApi)
        {
            _twitchApi = twitchApi;
            _twitchApi.Settings.ClientId = "";
        }
        // GET api/values
        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var result = await _twitchApi.Users.helix.GetUsersAsync(accessToken: "");
            string userName = result?.Users?.FirstOrDefault()?.DisplayName;
            return Ok(userName);
        }
    }
```

**Comment by Mahsaap** [comment] 2018-05-17 12:02
Someone previously had a similar issue with wpf, can you verify for me if your clientID actually get set?

**Comment by LuckyNoS7evin** [comment] 2018-05-17 12:15
@Mahsaap I can confirm it's a full framework issue.

1) doesn't work in WPF
2) doesn't work in MVC

clientID and access token used work in Core

**Comment by Mahsaap** [comment] 2018-05-18 12:31
@Iturio Just wanted to give you a heads up that we are in the process of moving the current issues to the respective modules. So since this is an active issue, we wanted you to know prior to moving. Will be moved to https://github.com/TwitchLib/TwitchLib.Api/issues

**Comment by D3thw0lf** [comment] 2018-05-30 17:05
Any update on this one? :) (not moved yet so I ask here)

**Comment by swiftyspiffy** [comment] 2018-06-15 23:10
I think this should be fixed. If you want to give it a go @Iturio and let me know. Updates are in latested Api package.

**Closed as completed** 2018-06-17 21:55 UTC

**Comment by Iturio** [comment] 2018-06-25 14:24
Hi @swiftyspiffy,
I just managed to upgrade to the newest version and can confirm: This is definitely fixed :)
Thank you all very much!
