### ISSUE TITLE
multiple Unaccounted for - please file issue messages

### ISSUE THREAD

**Issue by briermay** [TwitchLib/TwitchLib#473] opened 2020-02-28 18:48 UTC
#1: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership(please create a TwitchLib GitHub issue :P)

#2: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands (please create a TwitchLib GitHub issue :P)

#3: Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags(please create a TwitchLib GitHub issue :P)

**Comment by ZoPotato** [comment] 2020-07-16 07:33
Got the exact same issue

**Comment by swiftyspiffy** [comment] 2020-07-17 01:34
Apologies for the delay. These specific messages (CAP = capability) are intended to be ignored by the library. They don't relay any useful information and are caused by the client requesting said capabilities.

**Comment by swiftyspiffy** [comment] 2021-10-31 20:54
Capacity events are now silently ignored. Closing this.

**Closed as completed by swiftyspiffy** 2021-10-31 20:54 UTC
