### ISSUE TITLE
API V5 Channels seems broken.

### ISSUE THREAD

**Issue by hesa2020** [TwitchLib/TwitchLib#460] opened 2019-09-28 21:15 UTC
```
_client = new TwitchAPI();
_client.Settings.ClientId = "7ij5crf8xor3hxnkes3atm93vj96bzi";
_client.Settings.AccessToken = Properties.Settings.Default["TwitchBotKey"].ToString();

var followers = await _client.V5.Channels.GetAllFollowersAsync(HostName);
var subscriptions = await _client.V5.Channels.GetAllSubscribersAsync(HostName);
```

Both followers and subscriptions return BadRequestException exceptions

however 

```
var test = await _client.V5.Users.GetUserAsync();
```
Is working fine.

**Comment by Mahsaap** [comment] 2019-09-28 21:22
Make sure you have the permissions ad scopes. Subs would require streamer account not sure I'd the followers

**Comment by swiftyspiffy** [comment] 2019-09-28 22:12
Tested both, and both appear to be working.

You do not need the channel's oauth to get followers, but as @Mahsaap said, you do need it for the subscribers.
Additionally, you should be passing in the user id, not the username.

**Comment by AlaskanDruid** [comment] 2019-10-02 17:53
Hesa2020.\

Any luck on this? I don't think the library has been updated for 2019 yet. Lots of weird exceptions for every sample in this repository :(

**Comment by Mahsaap** [comment] 2019-10-02 17:55
Use Pre release , updated plenty

**Comment by Mahsaap** [comment] 2019-10-02 17:57
The samples has nothing to do with the errors. Twitch changing things and breaking. Release does need to be updated  badly however. But arm dev or pre release is more stable and patched

**Comment by AlaskanDruid** [comment] 2019-10-02 18:02
Thank you for the info. Newest pre-release has same issues. I'll wait until the library is ready for twitch (I wonder if Twitch changed tons of stuff recently).

**Comment by Mahsaap** [comment] 2019-10-02 18:03
Same issue? It works for many others. What's the error

**Comment by Mahsaap** [comment] 2019-10-02 18:05
If its unity that's completely different

**Comment by AlaskanDruid** [comment] 2019-10-02 18:09
all in pure C# :)

Just following the example to get a list of followers:

api = new TwitchAPI();
api.Settings.ClientId = "{ID HERE}";
api.Settings.AccessToken = "{ACCESS TOKEN HERE}";

var channelFollowers = await api.V5.Channels.GetChannelFollowersAsync("channel_id");

Despite providing the client id, and the access token with the proper permissions..

1. Your ClientID was invalid/not set.
2. Your refresh token was invalid.
3. You requested a username when the server was expecting a user ID.


1. ClientID is valid (it's set above).
2. There is no request for a "refresh token". Sounds like something internal to the TwitchLib.
3. I didn't request a username or user ID, I only provided the library's required Client_id.

**Comment by Mahsaap** [comment] 2019-10-02 18:13
Swift confirmed it worked for him above. 
Check that you have the proper scopes applied to the token. What's the channel Id you are using?

**Comment by AlaskanDruid** [comment] 2019-10-02 18:13
alaskandruid (all lower case)

**Comment by Mahsaap** [comment] 2019-10-02 18:15
That's not an I'd, that's your problem

**Comment by AlaskanDruid** [comment] 2019-10-02 18:23
ah haha! It is it is! Unfortunately, It looks like twitch removed the ability to get the channel_id a couple of days ago. I'll contact that them to find out when it will return so the APIs will be useful.

Thanks for your help!

**Comment by Mahsaap** [comment] 2019-10-02 18:28
Swifty has an extension for chrome if you only need one for say yourself. But if you need to programmable get it. Use getuserasync with the logins param (on helix) or getuserbyusername on v5. Then get the I'd from the returned object.

**Comment by LuckyNoS7evin** [comment] 2019-10-02 18:29
You can do it through the Helix Get Users endpoint it accepts Id or login

**Comment by AlaskanDruid** [comment] 2019-10-02 18:40
Hmm. Helix looks like the way. The other option requires some other kind of random token (auth token), but there's no sample/info on that.  Helix seems to accept null values (as who knows what the real values are needed). I'll poke around this some more. It's unfortunately that there are a crap tons of work around needed just to get a view count. Is it ok to submit working sample code somewhere?

**Comment by Mahsaap** [comment] 2019-10-02 18:45
var user = await _client.Helix.Users.GetUsersAsync(logins: new List<string>("alaskandruid"));
var id = user[0].id;

var user = await _client.V5.Users.GetUserByNameAsync("alaskandruid");
var id = user.id // Cant remember if you need [0] or not on that one.

**Comment by AlaskanDruid** [comment] 2019-10-02 18:54
I think we're pretty much on the same page. My code so far:

            var unknown = await api.Helix.Users.GetUsersAsync();
            Console.WriteLine("Users: {0}", unknown.Users.Length);
            Console.WriteLine("User: {0} : {1}", unknown.Users[0].Login, unknown.Users[0].Id);

            var channelFollowers = await api.V5.Channels.GetChannelFollowersAsync(unknown.Users[0].Id);
            Console.WriteLine("Followers: {0}", channelFollowers.Total);

            Console.WriteLine("View Count: {0}", unknown.Users[0].ViewCount);


Though this still leads to the channelId issue. (for subscriber count). I haven't found any code so far that returns that information (the user.id) returns the original errors (posted above) when passed:

List<Subscription> allSubscriptions = await api.V5.Channels.GetAllSubscribersAsync(unknown.Users[0].Id);

**Comment by Mahsaap** [comment] 2019-10-02 18:58
Subscriber does require a channel that is affiliate or partnered. And also the account oauthh for that channel.

**Comment by Mahsaap** [comment] 2019-10-02 19:00
If you get null return on any asynchronous call its possible.its notnsetupnproperly and alternatively you can use  .Result at the end of the call instead of using await. However this can make it possible to thread lock ui.

**Comment by AlaskanDruid** [comment] 2019-10-02 19:02
Ah, I understand. Sounds like there's a few things:

1. Need to get channel affiliated.
2. Need to find a twitch library that allows the ability to read subscriber count.

This is very good information to know.

Thank you for your help.

**Comment by swiftyspiffy** [comment] 2019-10-29 09:24
You’re call above to list all subscriptions was correct, but it’s an expensive call that can make many requests if the streamer has a large number of subscribers. You can also call GetSubscribers, which is a paginated result.

Going to close this. Feel free to reopen if needed.

**Closed as completed by swiftyspiffy** 2019-10-29 09:24 UTC
